//Product
export const SET_PRODUCTS = "SET_PRODUCTS";
export const GET_PRODUCTS_BY_ID = "GET_PRODUCTS_BY_ID";
export const CHANGE_PRODUCT_INPUT = "CHANGE_PRODUCT_INPUT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const SET_PRODUCT_MODEL = "SET_PRODUCT_MODEL";
export const REMOVE_PRODUCT_MODEL = "REMOVE_PRODUCT_MODEL";

//Home
export const SET_BANNERS = "SET_BANNERS";
export const SET_CAROUSELS = "SET_CAROUSELS";
export const SET_FIRST_TWOCAROUSELS = "SET_FIRST_TWOCAROUSELS";
export const SHOW_SCROLL = "SHOW_SCROLL";

//Category
export const SET_CATEGORY = "SET_CATEGORY";
export const SET_SINGLE_CATEGORY = "SET_SINGLE_CATEGORY";
export const CHANGE_CATEGORY_INPUT = "CHANGE_CATEGORY_INPUT";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const SET_CATEGORY_DETAILS = "SET_CATEGORY_DETAILS";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";

//cart
export const SET_CART_LIST = "SET_CART_LIST";
export const ADD_CART = "ADD_CART";
export const ADD_CART_PRICE = "ADD_CART_PRICE";
export const ORDER_CONFIRM = "ORDER_CONFIRM";

//Users
export const SET_SIGNUP = "SET_SIGNUP";
export const SET_LOGIN = "SET_LOGIN";
export const REMOVE_DEFAULT_LOGIN = "REMOVE_DEFAULT_LOGIN";
export const SET_DEFAULT_LOGIN = "SET_DEFAULT_LOGIN";
export const SET_USER = "SET_USER";
export const CHANGE_USER_INPUT = "CHANGE_USER_INPUT";
export const CHANGE_PASSWORD_INPUT = "CHANGE_PASSWORD_INPUT";
export const SET_USER_ERROR = "SET_USER_ERROR";
export const SET_ERROR = "SET_ERROR";
export const LOGOUT = "LOGOUT";
export const REMOVE_USER_MODEL = "REMOVE_USER_MODEL";
export const SET_USER_DETAILS = "SET_USER_DETAILS";
//Menu
export const SET_MENU_LIST = "SET_MENU_LIST";
export const SET_SESSION_PARENT_MENU = "SET_SESSION_PARENT_MENU";
export const SET_SESSION_CHILD_MENU = "SET_SESSION_CHILD_MENU";

// COMMON
export const CHANGE_PARAMETER_INPUT = "CHANGE_PARAMETER_INPUT";
export const SET_PARAMETER = "SET_PARAMETER";
export const SET_LOADING = "SET_LOADING";
export const CHANGE_DEMAND_PARAM_INPUT = "CHANGE_DEMAND_PARAM_INPUT";
export const SET_DEMAND_PARAMETER = "SET_DEMAND_PARAMETER";
export const CHANGE_PAGING_PARAMETER = "CHANGE_PAGING_PARAMETER";
export const PAGING_TOTAL_COUNT = "PAGING_TOTAL_COUNT";

export const REMOVE_PAGING_PARAMETER = "REMOVE_PAGING_PARAMETER";
export const REMOVE_DEMAND_PARAMETER = "REMOVE_DEMAND_PARAMETER";


//message
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

//BOOK
export const SET_BOOK_LIST = "SET_BOOK_LIST";
export const SET_DETAILS_BOOKS = "SET_DETAILS_BOOKS";
export const DROPDOWN_BRAND_LIST = "DROPDOWN_BRAND_LIST";
export const DROPDOWN_CLASS_LIST = "DROPDOWN_CLASS_LIST";
export const DROPDOWN_EDITION_LIST = "DROPDOWN_EDITION_LIST";
export const DROPDOWN_GROUP_LIST = "DROPDOWN_GROUP_LIST";
export const SET_DEMAND_LIST = "SET_DEMAND_LIST";
export const SET_AGENT_ORDER_LIST = "SET_AGENT_ORDER_LIST";
export const SET_AGENT_CHALLAN_LIST = "SET_AGENT_CHALLAN_LIST";
export const SET_DEMAND_DETAILS = "SET_DEMAND_DETAILS";
//report
export const SET_MENU_BASE64 = "SET_MENU_BASE64";
export const SET_ZILA_LIST = "SET_ZILA_LIST";
export const SET_LIBRARY_INFO_LIST = "SET_LIBRARY_INFO_LIST";

